### ISSUE TITLE
Complete No0B Here! How do I get this stuff working!?!

### ISSUE THREAD

**Issue by cavebear541** [ApertureLabsLtd/RFIDler#26]
I am at a complete loss as to how I am supposed to get my RFIDler working. Is there a way to just download a program that has all I need to get it working? The instructions in the read me are confusing and beyond my expertise. I need a guide for beginners!

**Comment by tonynaggs** [comment]
You need a Mac, Unix or Windows PC to connect to, and USB cable with a mini USB connector to connect to the Rfidler. (I have also heard of people connecting to an Android phone with USB OTG, but you probably need external power in this case.)

The Rfidler will look like a new serial port, and you can use your favourite terminal programming to connect & talk with it.

We really need to know what you're connecting your Rfidler to, and what you have done to set it up to in order to give more specific advice!

**Comment by cavebear541** [comment]
I'm connecting it to a PC.

**Comment by tonynaggs** [comment]
1. Our support forum is here: [http://rfidler.org/] (http://rfidler.org/)

2. "a PC" is not sufficient information for anyone to understand your problem and help you:
    you need to state what operating system (Mac OS, Linux, Windows, etc) and version you have,
    also what you have tried (software you have installed or struggled with),
    and what does & does not work (for example do the LEDs on the Rfidler light when you plug it in).

3. Github issues are for reporting bugs in the supplied software, or feature requests.
    Using the forum for support requests means more people can read your questions and offer replies.

**Comment by cavebear541** [comment]
I have Windows 7, when I plug the RFIDler into the computer the lights on the device light up.
My problem is that I don't know which software I need to be using. This website has a number of different ones it talks about using, none of which I can figure out. All I know how to do at this moment is how to plug the device into my computer. Does anyone know which software I need to download or an instruction manual is located?

**Comment by tonynaggs** [comment]
Cool, I'm using Windows 7 too.

My plan this week includes blogging on:
* How to use Rfidler with Windows XP or 7, including Windows bugs to work around and what tools to install.

* Features and roadmap for the Rfidler Windows tools I have written.

Sorry these don't exist already.

**Comment by fabiand93** [comment]
I'm using a Mac OS Yosemite, and I'm lost too
